Perfume.create(name: "Byredo 1996 Inez & Vinoodh", image_url: "https://fimgs.net/mdimg/perfume/375x500.19247.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Accord Oud", image_url: "https://fimgs.net/mdimg/perfume/375x500.10757.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Bal d'Afrique", image_url: "https://fimgs.net/mdimg/perfume/375x500.6458.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Baudelaire", image_url: "https://fimgs.net/mdimg/perfume/375x500.7458.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Belle De Tanger", image_url: "https://fimgs.net/mdimg/perfume/375x500.40622.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Bibliotheque", image_url: "https://fimgs.net/mdimg/perfume/375x500.43324.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Black Saffron", image_url: "https://fimgs.net/mdimg/perfume/375x500.16220.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Blanche", image_url: "https://fimgs.net/mdimg/perfume/375x500.6686.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Bullion", image_url: "https://fimgs.net/mdimg/perfume/375x500.15923.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Byredo", image_url: "https://fimgs.net/mdimg/perfume/375x500.40351.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Chembur", image_url: "https://fimgs.net/mdimg/perfume/375x500.3573.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Cuir Obscur", image_url: "https://fimgs.net/mdimg/perfume/375x500.40276.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Elevator Music", image_url: "https://fimgs.net/mdimg/perfume/375x500.48821.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Eleventh Hour", image_url: "https://fimgs.net/mdimg/perfume/375x500.50934.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Fantastic Man", image_url: "https://fimgs.net/mdimg/perfume/375x500.6688.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Flowerhead", image_url: "https://fimgs.net/mdimg/perfume/375x500.23881.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Green", image_url: "https://fimgs.net/mdimg/perfume/375x500.3574.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Gypsy Water", image_url: "https://fimgs.net/mdimg/perfume/375x500.3575.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Heliotropia", image_url: "https://fimgs.net/mdimg/perfume/375x500.40277.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Inflorescence", image_url: "https://fimgs.net/mdimg/perfume/375x500.17798.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo La Tulipe", image_url: "https://fimgs.net/mdimg/perfume/375x500.8441.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo M/Mink", image_url: "https://fimgs.net/mdimg/perfume/375x500.10758.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Mister Marvelous", image_url: "https://fimgs.net/mdimg/perfume/375x500.13002.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Mojave Ghose", image_url: "https://fimgs.net/mdimg/perfume/375x500.27040.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Oud Immortel", image_url: "https://fimgs.net/mdimg/perfume/375x500.10759.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Palermo", image_url: "https://fimgs.net/mdimg/perfume/375x500.12488.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Pulp", image_url: "https://fimgs.net/mdimg/perfume/375x500.3576.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Rodeo", image_url: "https://fimgs.net/mdimg/perfume/375x500.45540.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Rose Noir", image_url: "https://fimgs.net/mdimg/perfume/375x500.3577.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Rose of No Man's Land", image_url: "https://fimgs.net/mdimg/perfume/375x500.31931.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Russell Westbrook", image_url: "https://fimgs.net/mdimg/perfume/375x500.31423.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Seven Veils", image_url: "https://fimgs.net/mdimg/perfume/375x500.13307.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Byredo Slow Dance", image_url: "https://fimgs.net/mdimg/perfume/375x500.57007.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Angeliques Sous La Pluie", image_url: "https://fimgs.net/mdimg/perfume/375x500.1023.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Bigarde Concentree", image_url: "https://fimgs.net/mdimg/perfume/375x500.4770.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Carnal Flower", image_url: "https://fimgs.net/mdimg/perfume/375x500.1024.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Cologne Bigarade", image_url: "https://fimgs.net/mdimg/perfume/375x500.4769.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Cologne Idelebile", image_url: "https://fimgs.net/mdimg/perfume/375x500.30353.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Dans Tes Bras", image_url: "https://fimgs.net/mdimg/perfume/375x500.3976.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Dries van Noten par Frederic Malle", image_url: "https://fimgs.net/mdimg/perfume/375x500.17481.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Eau De Magnolia", image_url: "https://fimgs.net/mdimg/perfume/375x500.25042.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle En Passant", image_url: "https://fimgs.net/mdimg/perfume/375x500.2793.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle French Lover", image_url: "https://fimgs.net/mdimg/perfume/375x500.1022.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Geranium Pour Monsieur", image_url: "https://fimgs.net/mdimg/perfume/375x500.5911.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Iris Poudre", image_url: "https://fimgs.net/mdimg/perfume/375x500.4771.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle L'Eau D'Hiver", image_url: "https://fimgs.net/mdimg/perfume/375x500.2797.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Le Parfum de Therese", image_url: "https://fimgs.net/mdimg/perfume/375x500.4772.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Lipstick Rose", image_url: "https://fimgs.net/mdimg/perfume/375x500.2799.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Lys Mediterranee", image_url: "https://fimgs.net/mdimg/perfume/375x500.4640.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Monsieur", image_url: "https://fimgs.net/mdimg/perfume/375x500.32590.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Musc Ravageur", image_url: "https://fimgs.net/mdimg/perfume/375x500.1801.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Music For a While", image_url: "https://fimgs.net/mdimg/perfume/375x500.47795.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Noir Epices", image_url: "https://fimgs.net/mdimg/perfume/375x500.2800.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Outrageous!", image_url: "https://fimgs.net/mdimg/perfume/375x500.43456.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Portrait of a Lady", image_url: "https://fimgs.net/mdimg/perfume/375x500.10464.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Rose & Cuir", image_url: "https://fimgs.net/mdimg/perfume/375x500.56516.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Superstitious", image_url: "https://fimgs.net/mdimg/perfume/375x500.41322.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Une Fleur de Cassie", image_url: "https://fimgs.net/mdimg/perfume/375x500.4773.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Une Rose", image_url: "https://fimgs.net/mdimg/perfume/375x500.2851.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Frederic Malle Vetiver Extraordinare", image_url: "https://fimgs.net/mdimg/perfume/375x500.4774.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Ambrette 9", image_url: "https://fimgs.net/mdimg/perfume/375x500.6334.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Another 13", image_url: "https://fimgs.net/mdimg/perfume/375x500.10131.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Bergamote 22", image_url: "https://fimgs.net/mdimg/perfume/375x500.6327.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Fleur d'Oranger 27", image_url: "https://fimgs.net/mdimg/perfume/375x500.6331.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Geranium 30", image_url: "https://fimgs.net/mdimg/perfume/375x500.25986.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Iris 39", image_url: "https://fimgs.net/mdimg/perfume/375x500.6336.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Jasmin 17", image_url: "https://fimgs.net/mdimg/perfume/375x500.6337.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Labdanum 18", image_url: "https://www.fragrantica.com/perfume/Le-Labo/Labdanum-18-7848.html", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Lys 41", image_url: "https://fimgs.net/mdimg/perfume/375x500.18382.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Neroli 36", image_url: "https://fimgs.net/mdimg/perfume/375x500.6330.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Oud 27", image_url: "https://fimgs.net/mdimg/perfume/375x500.6329.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Patchouli 34", image_url: "https://fimgs.net/mdimg/perfume/375x500.6332.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Rose 31", image_url: "https://fimgs.net/mdimg/perfume/375x500.3678.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Santal 33", image_url: "https://fimgs.net/mdimg/perfume/375x500.12201.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo The Noir 29", image_url: "https://fimgs.net/mdimg/perfume/375x500.31872.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Tonka 25", image_url: "https://fimgs.net/mdimg/perfume/375x500.51697.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Vetiver 46", image_url: "https://fimgs.net/mdimg/perfume/375x500.6328.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Le Labo Ylang 49", image_url: "https://fimgs.net/mdimg/perfume/375x500.18383.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian 754", image_url: "https://fimgs.net/mdimg/perfume/375x500.20193.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian A La Rose", image_url: "https://fimgs.net/mdimg/perfume/375x500.29083.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Absolue Pour le Matin", image_url: "https://fimgs.net/mdimg/perfume/375x500.10470.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Absolue Pour le Soir", image_url: "https://fimgs.net/mdimg/perfume/375x500.10469.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Allegria", image_url: "https://fimgs.net/mdimg/perfume/375x500.21973.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Amyris", image_url: "https://fimgs.net/mdimg/perfume/375x500.15565.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Amyris Homme", image_url: "https://fimgs.net/mdimg/perfume/375x500.15566.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian APOM Pour Femme", image_url: "https://fimgs.net/mdimg/perfume/375x500.6805.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian APOM Pour Homme", image_url: "https://fimgs.net/mdimg/perfume/375x500.6806.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Aqua Celestia", image_url: "https://fimgs.net/mdimg/perfume/375x500.42268.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Aqua Universalis", image_url: "https://fimgs.net/mdimg/perfume/375x500.12710.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Aqua Vitae", image_url: "https://fimgs.net/mdimg/perfume/375x500.18854.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Baccarat Rouge 540", image_url: "https://fimgs.net/mdimg/perfume/375x500.33519.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Ciel de Gum", image_url: "https://fimgs.net/mdimg/perfume/375x500.21775.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Coloratura", image_url: "https://fimgs.net/mdimg/perfume/375x500.20192.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Elle 25", image_url: "https://fimgs.net/mdimg/perfume/375x500.10229.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Feminin Pluriel", image_url: "https://fimgs.net/mdimg/perfume/375x500.26253.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Floralia", image_url: "https://fimgs.net/mdimg/perfume/375x500.21972.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Grand Soir", image_url: "https://fimgs.net/mdimg/perfume/375x500.40816.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian L'eau A la Rose", image_url: "https://fimgs.net/mdimg/perfume/375x500.55118.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Le Beau", image_url: "https://fimgs.net/mdimg/perfume/375x500.34026.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Lumiere Noire Pour Femme", image_url: "https://fimgs.net/mdimg/perfume/375x500.6807.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Lumiere Noire Pour Homme", image_url: "https://fimgs.net/mdimg/perfume/375x500.6808.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Masculin Pluriel", image_url: "https://fimgs.net/mdimg/perfume/375x500.26252.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Oud", image_url: "https://fimgs.net/mdimg/perfume/375x500.14610.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Oud Cashmere Mood", image_url: "https://fimgs.net/mdimg/perfume/375x500.17661.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Oud Satin Mood", image_url: "https://fimgs.net/mdimg/perfume/375x500.30352.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Oud Silk Mood", image_url: "https://fimgs.net/mdimg/perfume/375x500.48456.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Oud Velvet Mood", image_url: "https://fimgs.net/mdimg/perfume/375x500.17660.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Maison Francis Kurkdjian Petit Matin", image_url: "https://fimgs.net/mdimg/perfume/375x500.40817.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Odin 00 Auriel", image_url: "https://fimgs.net/mdimg/perfume/375x500.34581.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Odin 01 Sunda", image_url: "https://fimgs.net/mdimg/perfume/375x500.9670.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Odin 02 Owari", image_url: "https://fimgs.net/mdimg/perfume/375x500.9671.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Odin 03 Century", image_url: "https://fimgs.net/mdimg/perfume/375x500.9672.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Odin 04 Petrana", image_url: "https://fimgs.net/mdimg/perfume/375x500.9673.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Odin 06 Amanu", image_url: "https://fimgs.net/mdimg/perfume/375x500.12720.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Odin 07 Tanoke", image_url: "https://fimgs.net/mdimg/perfume/375x500.14127.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Odin 08 Seylon", image_url: "https://fimgs.net/mdimg/perfume/375x500.16511.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Odin 09 Posala", image_url: "https://fimgs.net/mdimg/perfume/375x500.17090.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Odin 10 Roam", image_url: "https://fimgs.net/mdimg/perfume/375x500.18359.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Odin 11 Semma", image_url: "https://fimgs.net/mdimg/perfume/375x500.21772.jpg", likes: 1, dislikes: 0)
Perfume.create(name: "Odin 12 Lacha", image_url: "https://fimgs.net/mdimg/perfume/375x500.31895.jpg", likes: 1, dislikes: 0)

Comment.create(review: "Disgusting. When I put it on, I smell like a BEAST.", reviewer: "Kim R.", perfume_id: 1)
Comment.create(review: "BEAST?! How dare you?!", reviewer: "Eileen D.", perfume_id: 1)
Comment.create(review: "This scent makes me feel confident. Who gon' check me, boo?", reviewer: "Sheree W.", perfume_id: 2)
Comment.create(review: "Stunning. This fragrance makes me feel cool, not all like, uncool.", reviewer: "Countess LuAnn", perfume_id: 3)
Comment.create(review: "Word on the street is...this is better than La Dame by Karen for sure.", reviewer: "Gizelle B.", perfume_id: 4)
Comment.create(review: "Fabulous! GONE WITH THE WIND FABULOUS!", reviewer: "Kenya M.", perfume_id: 5)
Comment.create(review: "Great for any occasion! Makes me ready to whoop it up!", reviewer: "Vicki G.", perfume_id: 6)
Comment.create(review: "Not a fan. I just delete delete delete.", reviewer: "Vicki G.", perfume_id: 6)